matrix:
include:
language: c
sudo: false # only for faster builds
compiler:
 - clang
 - gcc
script:
 - gcc -o test pattern2.c
 - gcc -o test tree.c
 - gcc -o test diamond.c
 - gcc -o test triangle.c
 - ./pattern2
 - ./tree
 - ./diamond
 - ./triangle
 
