matrix:
include:
language: c
sudo: false # only for faster builds
compiler:
 - clang
 - gcc
script:
 - gcc -o  pattern2.c
 - gcc -o  tree.c
 - gcc -o  diamond.c
 - gcc -o  triangle.c
 - ./pattern2
 - ./tree
 - ./diamond
 - ./triangle
 
